### ISSUE TITLE
select 无法滚动(fixed)

### ISSUE THREAD

**Issue by Glimis** [iuap-design/iuap-design#12]
select 打开,滚动一下有惊喜...最笨,描述不出来

**Comment by Glimis** [comment]
包括date在内,bug/需求 都是一样的

**Comment by songhlc** [comment]
@Glimis 反馈问题的时候请详细一点，把具体问题，使用哪个组件以及在**哪个页面**可重现**哪个问题**描述清楚 比如照着官方文档哪个章节做出的例子是不正确的，把这些信息描述详细一点
