### ISSUE TITLE
部分描述错误

### ISSUE THREAD

**Issue by Glimis** [iuap-design/iuap-design#14]
## [评分](http://design.yyuap.com/dist/pages/plugins/jsrating.html")

```
再引入js: http://design.yyuap.com/static/raty/raty.js
```

中http://design.yyuap.com/static/raty/raty.js 不存在
## [面包屑](http://design.yyuap.com/dist/pages/components/breadcrumb.html)

第一个例子

``` html
<ol class="u-breadcrumb breadcrumb-arrow">
    <li><a class="icon md-home u-link" href="javascript:void(0)">Home</a></li>
    <li><a class="u-link" href="javascript:void(0)">Library</a></li>
    <li class="active">Data</li>
</ol>
```

. breadcrumb-arrow 不存在

**Comment by ahua52** [comment]
谢谢指出，已修复
