### ISSUE TITLE
有spa的解决方案吗?

### ISSUE THREAD

**Issue by Glimis** [iuap-design/iuap-design#15]
我们使用spa的方式,每次初始化都需要

``` javascript
u.compMgr.updateComp()
```

以上信息会初始化所有组件,不确定对已经初始化的组件是否还会再次初始化(比如spa中的导航)
有更合适的初始化方式吗?

因为直接使用ko,可以提供ko component 格式的组件吗?

**Comment by songhlc** [comment]
本身neoui并不依赖ko u.compMgr.updateComp()看看怎么放到baseview里统一执行吧
