### ISSUE TITLE
modal插件新建模式对话框的时候不支持html格式做为content传入

### ISSUE THREAD

**Issue by wyyew** [iuap-design/iuap-design#19]
modal插件新建模式对话框的时候不支持html格式做为content传入
window.md = u.dialog({id:_str, content:'#dialog_content', hasCloseMenu:true});
content现在支持传id,传文本，但是传了html格式的时候就会报错，请尽快修改，因为现在我正在用这个，我在本地的u.js文件里做了修改，怕以后更新还会出问题，如果做完修改之后请告知，谢谢！

**Comment by LiuYueKai** [comment]
好的，重构完之后会处理。

**Comment by LiuYueKai** [comment]
目前已经支持此方式。

window.md = u.dialog({id:'testDialg',content:'< div id="dialog_content">test</ div>',hasCloseMenu:true});
@wyyew
