### ISSUE TITLE
使用jekyll快速搭建静态博客

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/iuap-design#3]
建议前往这里学习jekyll的使用：http://jekyllcn.com/
## 基本用法

```
$ gem install jekyll
$ jekyll new docs
$ cd docs
$ jekyll serve
# => 打开浏览器 http://localhost:4000
```

**Comment by bengirl** [comment]
gem install jekylln    提示 bash:  gem:command not found.我该这么弄啊

**Comment by GuoYongfeng** [comment]
@benq1987 有easy_install吗

**Comment by bengirl** [comment]
没有呀，这个要安装吗？还我要去安装一个这个？https://rubygems.org/pages/download

**Comment by GuoYongfeng** [comment]
@benq1987 需要安装，另外，更多关于这个话题的讨论，已经迁移到 [使用jekyll快速搭建静态博客](https://github.com/iuap-design/blog/issues/3)
