### ISSUE TITLE
表格样式对齐问题

### ISSUE THREAD

**Issue by lixial** [iuap-design/iuap-design#33]
表格设置属性"showNumCol":true后，序号列和后面的列未对齐

![grid](https://cloud.githubusercontent.com/assets/22703996/19211747/8e7dbbec-8d76-11e6-8b72-a7f9895575ce.png)

**Comment by LiuYueKai** [comment]
请留一下Q之类的联系方式。

**Comment by lixial** [comment]
联系QQ：390652131

**Comment by LiuYueKai** [comment]
是由于浏览器显示比例不为100%导致，后续完善css保证所有比例都可用
