### ISSUE TITLE
表格编辑态时点击其它单元格会显示其它单元格内容

### ISSUE THREAD

**Issue by lixial** [iuap-design/iuap-design#34]
在表格一个单元格编辑时，如果鼠标点击另一个单元格的数据，此时正在编辑的单元格会显示鼠标点击的单元格中的数值覆盖了原有值。
步骤：1.点击图1中段值为A的单元格使处于可编辑状态；
2.点击图2绿色行的段长度列，此时第一步中处于编辑态的单元格内容就变化；
3.再次点击其他字段使其他字段变成可编辑状态，见图3，A的值变回之前值。
![edit1](https://cloud.githubusercontent.com/assets/22703996/19211783/8116f904-8d77-11e6-9a7b-055433634514.png)
![edit2](https://cloud.githubusercontent.com/assets/22703996/19211784/816ace8a-8d77-11e6-88c7-8b848ec208b3.png)
![edit3](https://cloud.githubusercontent.com/assets/22703996/19211785/8194f534-8d77-11e6-87c2-fc3f25884685.png)

**Comment by lixial** [comment]
联系方式：QQ号390652131

**Comment by LiuYueKai** [comment]
onBeforeEditFun返回false之后没有取消掉编辑状态，已修改
