### ISSUE TITLE
建议新增的文档

### ISSUE THREAD

**Issue by DINLiang** [iuap-design/iuap-design#39]
1、neoui和kero写法对比文档
2、各个组件的使用方法（非动态生成，动态生成）
3、整体的uui实现一个效果的思路（ui层，dom层，数据层）
4、常见错误总结，分析文档

**Comment by GuoYongfeng** [comment]
@DINLiang 这个问题较大，请拆分成具体的问题并形成描述后单独提issue。
再次感谢提出这些问题。
