### ISSUE TITLE
表格编辑时回车键进入下一个单元格控制问题

### ISSUE THREAD

**Issue by lixial** [iuap-design/iuap-design#41]
grid操作时可以使用回车键进入下一个表格单元格，但是有的编辑项已经在onBeforeEditFun方法里进行了控制使该单元格不能编辑，但是点击回车键可以直接接入不能编辑的单元格，使该单元格变成可编辑状态。

**Comment by lixial** [comment]
联系人QQ：390652131

**Comment by LiuYueKai** [comment]
已解决
