### ISSUE TITLE
u.showLoader({})与u.dialog()两个组件存在兼容问题，会因为遮罩层问题出错

### ISSUE THREAD

**Issue by Anryliu** [iuap-design/iuap-design#46]
u.showLoader({})与u.dialog()两个组件存在兼容问题，会因为遮罩层问题出错
![image](https://cloud.githubusercontent.com/assets/8381491/20162449/2410a480-a730-11e6-91da-deeb26e575d4.png)

**Comment by LiuYueKai** [comment]
已修改，11月18之后的cdn版本将包含此次修改
