### ISSUE TITLE
[数字营销-需求] message控件需要能够自定义样式，包括位置，宽度，展现和消失时的动画

### ISSUE THREAD

**Issue by Free-Mind** [iuap-design/iuap-design#47]
1.message位置，目前只支持center和bottom，不够灵活，希望能够自定义top、bottom、right的大小，确定message的具体位置，
2.message的宽度需要根据里面的内容动态的变化。
3.目前message出现的方向是从底部向上进入，需要能够自定义message的展现动画

**Comment by LiuYueKai** [comment]
u.showMessage可通过参数template来控制显示的dom结构。
但是要更加个性化的话建议直接创建组件来实现。
