### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by jiangtao** [iuap-design/iuap-design#5]
-  增加较难的命名空间， 比如`bootstrap`，木有命名空间，所以后来者，只能写一些`hard code`, 比如 `!important`覆盖。这点做的比较好的，可参考 `weui`
-  是否考虑`无障碍设计`
- 增加相关的example
- 重大的commit 还是写点备注吧

**未完待续...**

**Comment by GuoYongfeng** [comment]
@Jerret321 

1.我们在样式名前面加上"u-"来标识
2.无障碍设计是....

**Comment by bluemind7788** [comment]
@Jerret321 
bootstrap没加命名空间的做法确实不好，尤其是用一些基于bs的第三方库，样式上再覆盖样式确实抓狂；
weui加了‘weui’的前缀，对于一般的项目来说，不会用太多的样式库的，加上单字符的前缀完全可以了；
无障碍设计以后会考虑加入，不过是时间问题了，毕竟不是现在的重点

**Comment by jiangtao** [comment]
@GuoYongfeng http://www.w3cplus.com/wai-aria/wai-aria.html 有时间可以搞下。 其他的问题我在看。。
