### ISSUE TITLE
iuap-design 设计语言

### ISSUE THREAD

**Issue by cavenliu** [iuap-design/iuap-design#8]
# iUAP Design 设计语言

在企业级应用开发中，因为产品的项目化实施产品及定客户制化程度较高，在实现过程中尤其是前端的实现，会有不同的设计及交互规范，然而这里规范中存在大量的雷同控件、页面、交互模式及实现方式，这些重复性的工作对产品参与人员，尤其是设计、开发等角色来说是个困扰和折磨，也带来了巨大的开发及管理成本，降低了互联网时代的开发效率。iUAP Design是沉淀用友服务企业20年技术经验，总结而出的一个企业互联网应用设计语言。

iUAP Design开放 自由 轻量 生态  ，旨在重塑企业应用研发模式，解放设计，整合资源，提高效率，让研发团队更关注业务、效率提升用户体验。

iUAP Design致力于提升”终端用户”、“UE设计”、“弱前端开发”等角色的使用体验。它模糊了研发角色（产品、交互设计师、UI设计师、前端开发工程师）原本清晰的界限，使用该语言，可以高效率快速产生体验一致、直接可用的前台最终html页面。

使用iUAP Design可以快速地对整个产品前端界面进行深度定制，使整个界面保持高度一致而无需让工程师在此耗费更多精力，用户所需要做的就是下载iUAP Design框架，然后开工就可以了。用户可以参考这套系统的详细文档说明及丰富的样式版、模版，快速生产符合iUap生态的优质应用，轻松地调用iUap Design核心视觉组件和交互模式，产出最佳方案。
# iUAP Design 特性
## 细微：

原子化设计方法解构界面元素

iUAP Design提供精心设计的极简控件、组件
## 多维：

服务设计关注全方位体验

iUAP Design尽可能多的的关注用户体验地图上的触点及角色
## 预知：

设计思维指引目标导向

使用iUAP Design，参照样式版＋模版库，可预知产品形态
# iUAP Design 设计原则
### 活力美观
# iUAP Design 设计基础

文字
文案
色彩
图标
布局
动画微交互
# 字体（文字排版）

在iUAP Design中，为了兼容不同场景／终端的需求，达到更好的平衡，我们规定了新的字体家族及默认设置：

font-family:  ‘Open Sans’,’Helvetica Neue’,Arial,’Hiragino Sans GB’,’Microsoft YaHei’,sans-serif;
font-size:  13px;
line-height:  1.7;（1.38这个间距有待验证）
color:   #424242;
为保证更好的展示，我们增加了补充字体家族用于对应场景：

衬线字体font-family: Georgia, “Times New Roman”, Times, serif    不推荐在小字号使用，用于特殊文字或者标题中；
等宽字体font-family: Monaco, Menlo, Consolas, “Courier New”,     用来显示程序代码。

字体、字号建议：

大于14px的文字，特别是大于16px的文字，禁用宋体。
对于正文<p>，建议优先使用宋体（用12px和14px等偶数字体显示），建议禁用雅黑（大段可读性差）  
对于UI类元素 (按钮、标签) ，优先使用微软雅黑（用13px和15px等奇数字体显示）  
大于1440*900的显示器，大段12px文字显示感觉比较小，大段文章阅读困难，使用13-14px。  
对于企业ERP业务类应用，设计表单表格较多，12-13px优先。    

文本配色：
对比度过强过弱，都会难以阅读。这一点在深色背景下尤其明显。要获得良好的辨识度，文本应当满足最低的对比度，即4.5:1（依据明度计算）。
最适合阅读的对比度是7：1。对于某些非典型用户（老年、色盲、色弱）要酌情考虑。

建议最佳行长度：
每行中包含60个字符左右会使用户得到良好的阅读体验。

多语言：
纯英文环境字体可以考虑以下组合："Helvetica Neue",Helvetica,Arial,sans-serif
# 排版（页面元素布局）
## iUAP Design 营造会呼吸的界面

界面透气通畅
拥挤的布局会对用户产生压抑紧张感。适当的留白与干净的布局能使得界面舒缓流畅／亲切自然。
设计原则：
使信息元素在审美布局范围内最佳呈现
1、均衡（对称与平衡）
平衡的目的是营造和谐与稳定，给用户安全可靠的心理预期。
2、节奏 
基于视觉引导的有机视觉流和逐行扫描信息流。通过精心设计，引导用户视觉流向。
在元素间创造视觉流、信息流。在视觉引导下，使信息流保持一致、有机、可预见的自然流动。
视觉引导流向
3、层次
层次基于信息块的优先级：通过布局使不同权重的块元素产生层次感
避免单调的方法就是丰富的层次感，比如字体的粗细大小、背景色的深浅与模糊、配色的色阶色相变化、块元素的大小关系，适度的比例与层次营造生动的和谐感觉。
4、强调主体
支配性元素要重点显示处理。
5、统一
横平竖直互为参照。
类似元素要保持视觉一致性，营造大的区块感觉，避免零散。
构图原则：
构图的目标：使元素各归其位，服务功能与审美
使用网格（栅格）：
使用网格设计，建立秩序，保持界面的灵活与一致，满足不用端。
页面元素大小／元素间距关系在布局中的尺寸通过精细网格来完成布局：

所有组件都基于间隔为 8px的基准网格对齐。
排版/文字（Type）基于间隔为 4px 的基准网格对齐。
在工具栏中的图标基于间隔为 4px 的基准网格对齐。
以上规则适用于移动设备、平板设备以及桌面应用程序。
# 色彩
## iUAP Design 塑造有活力的企业应用色彩。

iUAP Design 基础配色包含：主题色，强调色（或称关键色）及辅助色。取色板－－》色板

色彩实用建议：为营造独特的使用氛围。先需要选用一种主题色，一种强调色（或称关键色），向用户呈现自己的品牌特征（主题色）的同时，创造出对比（强调色）。其余的辅助部分一般使用亮色或者暗色主题所规定的色板。
iUAP Design 界面以3～5种颜色决定了整体色调。主要颜色会用在菜单、导航、链接、高亮选项等。

文字用色建议：

白色背景上的文字，标准 alpha 值为 87%（#000000）。
视觉层次偏低的次要文字，应该使用 54%（＃000000）的 alpha 值。
正文和标签中用于提示用户的文字，视觉层次更低，应该使用26%（#000000）的 alpha 值。
彩色背景上白色或黑色文字，可以通过表格中的调色板找到合适的色彩对比度和 alpha 值。

配色设计要点

主张使用较明亮的颜色，前景和背景对比鲜明，易于区别。
配色表中的每种颜色都可以在亮度上上下浮动10%左右来生成一个相近但又有些许不同的颜色作为边框及悬停渐变使用。
在界面中运用的所有配色尽量使用配色表中已列明的颜色；
优先使用主要颜色和灰度颜色，仅在特殊的按钮或消息时才使用额外颜色。
# 图标

使用开源字体图标“Font Awesome”

http://www.bootcss.com/p/font-awesome/

一个字体文件， 249 个图标

一个字体文件包含了所有图标。Font Awesome 助你完整表达web页面上每个动作的含义。

用CSS控制样式

用CSS能非常容易的改变这些图标的颜色、大小、阴影以及任何CSS能控制的属性。

无限缩放

矢量图意味着每个图标都能在所有大小的屏幕上完美呈现。

个人、商业均可自由使用

Font Awesome是完全免费的，无论个人还是商业使用。

支持IE7+

Font Awesome支持IE7及以上浏览器。

在Retina屏幕上也能完美呈现

Font Awesome 中包含的都是矢量图标，在高分辨率的显示器上也能完美呈现。

设计师的助手

安装 FontAwesome.otf 字体文件，然后在这个页面直接拷贝粘贴图标字符的代码就可以用于你的设计中了。

兼容屏幕阅读器

Font Awesome 不会阻止屏幕阅读器，这和其他图标字体的行为方式完全不同。

完美的 14px 字号

每个图标都是重新制作的，并且针对Bootstrap的默认14px字号做了最大的优化。

瘦身 28%

虽然增加了 16% 的图标，3.0 版本的体积却变得更小了。 Font Awesome 还可以定制，将你不需要的图标去掉。
# 文案

对互联网及软件而言：

常见的界面设计文案如下：

1、图标文字说明

2、表单示例和说明。

3、按钮标签。

4、流程提示。

5、政策（操作规矩）说明。

文案的基本原则：

明确第一（涵义要明确）、提示语应该清晰准确  
更有效、更简洁  
有“人情味”  
文案要符合整个产品的气质和目标用户
# 动画微交互
## 让产品“活”起来

微交互能够让用户在不自知的情况下被吸引——这也是设计要做的最重要的事情之一：让操作任务变得自然、清晰和尽可能的流畅。设计中有很多方法去提升微交互的效果，界面动效就是其中之一。
动效最重要和最原始的目的是让交互过程变得更清晰、轻松和轻快，动效的基础是实用性，不是纯粹的装饰和娱乐。

微交互中运用动效的原则：
·它不应该给页面加载徒增太重的负担
·它应该充分考虑目标用户可能使用的各种设备，以及可能出现的各种情况
·它不应该让那些专注页面的用户太过分心
·它应该和网站或app的整体风格相搭配，保证产品整体的和谐
·它柔和、轻盈、顺畅、自然

在iUAP Design中，动画微交互定义为一些轻微的，察觉度较低的界面动作，例如颜色变化，形状改变，位置移动，隐藏显示，遮罩阴影等。
产品融入动画微交互目的是为了通过细致入微的使用体验，堆积起用户对于产品的满意和快感，让减弱用户操作过程中的枯燥情绪，增加愉悦度及主动性行为。甚至用户会主动去频繁的使用和操作。这就是‘参与感’的表现，当一个用户在使用的过程中，能够随时的获取愉悦的反馈，那么这个产品的参与感是很强的，用户的存在感是很强的。

微交互的设计中，各种配色、形状、动态所形成的界面反馈，总的来说有3种作用：
第一，提供状态信息；引导用户使用
第二，展示结果信息；表示状态
第三，为用户操作提供帮助和引导。提示操作的结果

加入动画微交互后可以有效达到：
加强体验舒适度 
增加界面的活力 在用户预期之外增加的惊喜，可以是帅气的，可以是卖萌，可以有些物理属性，总之让用户感知到产品的生命力。 吸引用户持久的注意力，增加用户的惊喜感，在数据量较大的界面中添加一些动效，让用户保持注意力。

减弱不可避免的不适感  
让等待变得更愉快 常出现在加载、刷新、发送等界面中，让等待变得可视化，甚至不再那么无聊。   增加界面与界面衔接的延续感  界面的跳转不可以避免，但是如果让本来分别独立的2个界面或者事件拥有了特定的联系，可以显得更加好玩，不再是生硬的跳转。

可以带给用户反馈的界面呈现方式包括了：

1）按键和按钮；
2）渐变或透明；
3）动态的图标；
4）临界位置的动态效果；
5）高对比度高反差的色彩；
6）气泡或悬浮信息；
7）一闪而过的提示文字；
8）对应位置的形状/动态变化。

**Comment by GuoYongfeng** [comment]
@cavenliu 

后续可以使用简单的 `markdown` 语法编辑

**比如**

```
# iUap Design 特性

## 细微

原子化设计方法解构界面元素

iUap Design提供精心设计的极简控件、组件

## 多维
```

渲染之后为：

# iUap Design 特性

## 细微

原子化设计方法解构界面元素

iUap Design提供精心设计的极简控件、组件

## 多维

**Comment by GuoYongfeng** [comment]
@cavenliu 建议将整体内容梳理后迁移到：https://github.com/iuap-design/iuap-design-language
